#!/usr/bin/env bash
# Installs HAProxy with the following configurations:
# - Enables management via the init script.
# - Distributes requests using a round-robin algorithm.

sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend britfitzm.tech
    timeout client  30000
    bind 0:80
    default_backend britfitzm.tech_backend

backend britfitzm.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 284682-web-01 34.207.222.246:80 check
    server 284682-web-02 54.175.143.243:80 check
EOT

sudo service haproxy restart
